### ISSUE TITLE
issue rwequest UwU

### ISSUE THREAD

**Issue by davidjs11** [Alux6/HAcktoberfestTry#1]
Hii~~Hii~~

I fixie wixied the JSON-api fucksy wucksie!!! xpp

I repwaced the Prototypes.func wiff a more ~streamylined~ kawaii Pwototypiee.funkywunks object that make the JS logo go sooper dooper fast!! xD *starts twerking*

I fixie wixied the JSON-api fucksy wucksie!!! xpp

I repwaced the Prototypes.func wiff a more ~streamylined~ kawaii Pwototypiee.funkywunks object that make the JS logo go sooper dooper fast!! xD *starts twerking*

Can u pwease merge my pwull wequest senpai?!! UwU

**Comment by Alux6** [comment]
No thanks
